/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Login.Login;
import Login.loginDAO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class LogIn extends javax.swing.JFrame {

    Login lg;
    loginDAO logDao;

    public boolean validarLogin() {
        lg = new Login();
        logDao = new loginDAO();
        String correo = txtUsername.getText();
        String password = String.valueOf(txtPassword.getText());
        boolean validacion = false;
        try {

            if (!"".equals(correo) || !"".equals(password)) {

                System.out.println(logDao.log(correo, password));
                lg = logDao.log(correo, password);
                if (lg.getCorreo() != null && lg.getPassword() != null) {
                    validacion = true;
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales invalidas");
                }
            }
        } catch (NullPointerException ex) {
            JOptionPane.showConfirmDialog(null, "Error datos vacios " + ex.getMessage());
        }
        return validacion;
    }
    

    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        btnSingIn = new javax.swing.JButton();
        lblFotoPerfil = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        imgFondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogin.setBackground(new java.awt.Color(153, 153, 153));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSingIn.setBackground(new java.awt.Color(248, 147, 31));
        btnSingIn.setForeground(new java.awt.Color(20, 35, 61));
        btnSingIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtnSignIn.png"))); // NOI18N
        btnSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingInActionPerformed(evt);
            }
        });
        panelLogin.add(btnSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 111, 30));

        lblFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FotoLogIn.png"))); // NOI18N
        panelLogin.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 101, 101));

        lblpassword.setForeground(new java.awt.Color(204, 204, 204));
        lblpassword.setText("Password");
        panelLogin.add(lblpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        lblUsername.setForeground(new java.awt.Color(204, 204, 204));
        lblUsername.setText("Username");
        panelLogin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtUsername.setBackground(new java.awt.Color(30, 38, 61));
        txtUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        panelLogin.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 190, 30));

        txtPassword.setBackground(new java.awt.Color(30, 38, 61));
        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setText("admin");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, 30));

        imgFondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoLogIn.png"))); // NOI18N
        panelLogin.add(imgFondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSingInActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getBtnSingIn() {
        return btnSingIn;
    }

    public void setBtnSingIn(JButton btnSingIn) {
        this.btnSingIn = btnSingIn;
    }

    public JLabel getImgFondoLogin() {
        return imgFondoLogin;
    }

    public void setImgFondoLogin(JLabel imgFondoLogin) {
        this.imgFondoLogin = imgFondoLogin;
    }

    public JLabel getLblFotoPerfil() {
        return lblFotoPerfil;
    }

    public void setLblFotoPerfil(JLabel lblFotoPerfil) {
        this.lblFotoPerfil = lblFotoPerfil;
    }

    public JLabel getLblUsername() {
        return lblUsername;
    }

    public void setLblUsername(JLabel lblUsername) {
        this.lblUsername = lblUsername;
    }

    public JLabel getLblpassword() {
        return lblpassword;
    }

    public void setLblpassword(JLabel lblpassword) {
        this.lblpassword = lblpassword;
    }

    public JPanel getPanelLogin() {
        return panelLogin;
    }

    public void setPanelLogin(JPanel panelLogin) {
        this.panelLogin = panelLogin;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSingIn;
    private javax.swing.JLabel imgFondoLogin;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
